spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/worldbuilder_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true